const actionTypes = Object.freeze({
  //app
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  
  //user
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //admin
  FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
  FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

  FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
  FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',

  FETCH_REQUIRED_DOCTOR_Infor_START: 'FETCH_REQUIRED_DOCTOR_Infor_START',
  FETCH_REQUIRED_DOCTOR_Infor_SUCCESS: 'FETCH_REQUIRED_DOCTOR_Infor_SUCCESS',
  FETCH_REQUIRED_DOCTOR_Infor_FAILED: 'FETCH_REQUIRED_DOCTOR_Infor_FAILED',
});

export default actionTypes;
